### ISSUE TITLE
Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'

### ISSUE THREAD

**Issue by jricke** [Azure/azure-functions-eventhubs-extension#55]
Getting this periodically from the EventHubListener. Any help is appreciated.

Time	4:56:17 PM
Exception type	System.AggregateException
Exception message	Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.
LogLevel	Error
Category	Host.Triggers.EventHub
HostInstanceId	41890ee6-adff-43c7-aec1-25745d35eb7d
System.AggregateException: An error occurred while writing to logger(s). (Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.
   at System.Collections.Generic.DictionaryExtensions.GetValueOrDefault[T](IDictionary`2 dictionary, String key) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Shared\DictionaryExtensions.cs:line 13
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.StartTelemetryIfFunctionInvocation(IDictionary`2 stateValues) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 468
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.BeginScope[TState](TState state) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 435
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   at Microsoft.Extensions.Logging.LoggerExtensions.BeginFunctionScope(ILogger logger, IFunctionInstance functionInstance, Guid hostInstanceId) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\Logger\LoggerExtensions.cs:line 64
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 110
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56
   at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.EventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 messages)
   at Microsoft.Azure.EventHubs.Processor.PartitionPump.ProcessEventsAsync(IEnumerable`1 events)
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.
   at System.Collections.Generic.DictionaryExtensions.GetValueOrDefault[T](IDictionary`2 dictionary, String key) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Shared\DictionaryExtensions.cs:line 13
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.StartTelemetryIfFunctionInvocation(IDictionary`2 stateValues) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 468
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.BeginScope[TState](TState state) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 435
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)<---

**Comment by jricke** [comment]
After manually deleting all files on the Azure function and redeploying, the error is gone.

**Comment by jricke** [comment]
Error has presented itself again. Trying to delete files and redeploy did not work this time.

**Comment by FlavioDiasPs** [comment]
I am also facing this, have you solved it?

**Comment by jricke** [comment]
Haven't been able to solve it. Current work around is to recompile the source with the following method returning false:

https://github.com/Azure/azure-functions-eventhubs-extension/blob/daab3ae8a8e08dd971b8f9b19d52f09ef44af081/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Listeners/EventHubListener.cs#L330

**Comment by alrod** [comment]
+ @lmolkova

**Comment by pherbel** [comment]
Same here. It seems it is a bug in the AppInsights Logger.

Any update?
@alrod 
@lmolkova

**Comment by AaronKoller** [comment]
I am having the same issue too.

**Comment by galvesribeiro** [comment]
Folks have anyone got it fixed??? This is a very critical thing as no messages are able to being processed anymore with the EventHubs trigger...

**Comment by galvesribeiro** [comment]
Finally got it working...

Rever to `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.0.1" />` and it should work again...

**Comment by pherbel** [comment]
@galvesribeiro 
Yeah, Only the revert was an option for us too. 
The latest bits are still broken.

**Comment by arek-avanade** [comment]
Facing the same issue. Azure team, any update?

**Comment by bradjones11** [comment]
I came across the same issue today. The function app had not been changed for a while. To work around the issue I recreated the function app.

**Comment by prayashsharma** [comment]
I got the same exception today. Reverting back from 4.1.1 to 4.0.1 resolved the issue.

**Comment by sukhdeepsingh1** [comment]
Can this be taken on priority please, unable to use the latest version 4.1.1 because of it?

**Comment by lmolkova** [comment]
I'll have a look ASAP

**Comment by marcin2x** [comment]
Same issue for us. Reverting back from 4.1.1 to 4.0.1 worked fine.

**Comment by kroffdaddy** [comment]
Do you know if there will be a fix for this any time soon @lmolkova ?

**Comment by lmolkova** [comment]
I've tried to repro the issue with 
- Microsoft.Azure.WebJobs.Extensions.EventHubs 4.1.1
- Microsoft.NET.Sdk.Functions 3.0.9, 3.0.7
- Functions v3
- single event dispatch and multiple dispatch

I cannot repro with any of the above configurations, can someone please share:
- what other packages are used and versions
- any specific configuration applied?
- any other context?
- share the code (csproj, function definitions, strip anything sensitive)

Also, the initial description mentions  that error happens 'periodically'. Does it mean it reproduces from time to time?

**Comment by andrewjw1995** [comment]
I'm using:

 - Microsoft.Azure.WebJobs.Extensions.EventHubs 4.1.1
 - Microsoft.NET.Sdk.Functions 3.0.7
 - Microsoft.Azure.Functions.Extensions
 - Functions v3

I'm unable to reproduce this when running locally, it only happens to me when I deploy to an Azure Functions app on a dedicated App Service Plan. Also, interesting to note, this does not happen if I'm publishing messages using the legacy `WindowsAzure.ServiceBus` package for .NET Framework. Have a look at my [question on Stack Overflow](https://stackoverflow.com/q/63716454/2363967) for more details.

I've been trying to find the cause of this for a week now, and am still unable to reproduce it outside of my production code. I will post it here if I am successful in creating a minimal example

**Comment by jricke** [comment]
I experienced this problem on a contract and no longer able to provide updates. At the time, we were running in a dedicated app service plan and the problem only happened in Azure; local debug worked with no issues.

**Comment by lmolkova** [comment]
Still cannot repro with a dedicated plan in Azure.

> this does not happen if I'm publishing messages using the legacy WindowsAzure.ServiceBus package for .NET Framework. 

this is expected. The legacy package does not propagate context for tracing, so `Activities` are not created to represent such context and there is nothing to cast.

I suspect it has something to do with https://github.com/Azure/azure-functions-host/issues/5874 and having multiple versions of Activity type.

@andrewjw1995  can you please check something?
- open  kudu : https://\<your function-app\>.scm.azurewebsites.net 
- Open Process Explorer
- find w3wp (that is NOT scm)
- open Modules
- find how many System.Diagnostics.DiagnosticSource libs do you have and which versions

Thanks!

![image](https://user-images.githubusercontent.com/2347409/92963632-a0638500-f427-11ea-9daa-a68e446d4d4d.png)

**Comment by andrewjw1995** [comment]
I'm sorry @lmolkova, after downgrading to 4.0.1 and then back up to 4.1.1 I can no longer reproduce the issue. I've reverted the repository, deleted the bin and obj folders, and published with `Delete existing files`, but everything is working as expected now

**Comment by lmolkova** [comment]
@andrewjw1995 thanks for the update.

Can please someone who still has the issue help by checking number of DiagnosticSources versions?

* open kudu : https://<your function-app>.scm.azurewebsites.net
* Open Process Explorer
* find w3wp (that is NOT scm)
* open Modules
* find how many System.Diagnostics.DiagnosticSource libs do you have and which versions

Also, it seems redeploying function with "Delete existing files" flag seems to mitigate the issue. Please try and let us know.

**Comment by Henery309** [comment]
@lmolkova I am also getting this error.

**Comment by Henery309** [comment]
Update - I Deployed a brand new azure function app and still gives me the exact error.

**Comment by larsonmpdx** [comment]
I had the same problem as Henery309 with the same versions. redeploying with "delete existing files" turned on didn't fix it.  downgrading to Microsoft.Azure.WebJobs.Extensions.EventHubs 4.0.1 did fix it.

**Comment by isaacabraham** [comment]
Today I had the unenviable task of telling a customer of mine that around 40% of their Azure bill over the last few months has been comprised of exceptions being sent to AI thanks to this bug.

Having now seen this was opened six months ago, they are not very happy.

**Comment by dwoldo** [comment]
> Still cannot repro with a dedicated plan in Azure.
> 
> > this does not happen if I'm publishing messages using the legacy WindowsAzure.ServiceBus package for .NET Framework.
> 
> this is expected. The legacy package does not propagate context for tracing, so `Activities` are not created to represent such context and there is nothing to cast.
> 
> I suspect it has something to do with [Azure/azure-functions-host#5874](https://github.com/Azure/azure-functions-host/issues/5874) and having multiple versions of Activity type.
> 
> @andrewjw1995 can you please check something?
> 
> * open  kudu : https://<your function-app>.scm.azurewebsites.net
> * Open Process Explorer
> * find w3wp (that is NOT scm)
> * open Modules
> * find how many System.Diagnostics.DiagnosticSource libs do you have and which versions
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/2347409/92963632-a0638500-f427-11ea-9daa-a68e446d4d4d.png)

I am experiencing this issue locally with version Microsoft.Azure.WebJobs.Extensions.EventHubs 4.1.1

There was work dealing specifically with List<Activity> [here](https://github.com/Azure/azure-functions-eventhubs-extension/commit/371e9ff6b8b5eb24c5300e99b643b104c340533d#diff-195d2c9ccd88ec324d536317b700333aR201).

Looking at messages published to EventHubs, Some have correlationId with a Guid value and others have the key correlationId set but no value. They all have Diagnostic-Id. When correlationId is empty, I get the exception. When it contains a value, I do not have it.

![image](https://user-images.githubusercontent.com/10914645/95792869-5255d180-0cb2-11eb-9101-993f052d4c16.png)

**Comment by pietersap** [comment]
Any update, please? 

Regarding our System.Diagnostics.DiagnosticSource.dll: same as Henery309

**Comment by drdamour** [comment]
we started getting this recently, but not list, instead it was array 
```
Unable to cast object of type 'System.Diagnostics.Activity[]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.
```

looked in kudu and we do have two diagnostics
![image](https://user-images.githubusercontent.com/1514496/100026922-ea160780-2da8-11eb-9020-b4078feb4b26.png)

i'm attaching the output from app insights
[error.txt](https://github.com/Azure/azure-functions-eventhubs-extension/files/5586418/error.txt)


base on that output with the aggregate look slike it's a cascading failure

**Comment by drdamour** [comment]
yeah it's def aroudn this beginscope stuff added between 4.0.1 and 4.1.1 https://github.com/Azure/azure-functions-eventhubs-extension/compare/v4.0.1...v4.1.1#diff-8b6b4a74a02d0093520339d9c85feab675b851368b43aa1be96dea688b37cdd1R213

**Comment by AndreiHushchyn** [comment]
Hi, maybe it is related to this issue. https://github.com/dotnet/runtime/issues/47008
I fixed this locally by adding explicit package reference to my project 
<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.7.0">
      <NoWarn>NU1605</NoWarn>
</PackageReference>

**Comment by yvztzn** [comment]
@lmolkova We are facing the same error (I guess). The error message is slightly different.

> An error occurred while writing to logger(s). (Unable to cast object of type 'System.Diagnostics.Activity[]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.)

It started with the addition of a custom telemetry initialiser which is in a different project.

Company.Project.Shared.ApplicationInsights is a .NET Standard project which has a dependency to Microsoft.ApplicationInsights 2.16.0 which itself has a dependency to System.Diagnostics.DiagnosticSource 5.0.0. The project Company.Project.Component is an Azure Function App project referencing the shared project (both in the same solution).

We have 4 environments (each a dedicated Azure subscription) to which the application is deployed to. In the production environment I do not have enough rights but I can say that in all other 3 environments the assembly System.Diagnostics.DiagnosticSource.dll is loaded twice with the versions 4.700.20.56604 and 5.0.20.51904. I expect that production is the same.

In dev and test environments there is no exception. It might be that most likely these environments do not have heavy load. In preprod and prod environments the exception occurs and it happens to be the same EventHub. The following Application Insights query

```
exceptions
| where problemId startswith "System.InvalidCastException"
| distinct tostring(customDimensions["prop__{OriginalFormat}"])
```

returns a bunch of items

```
Error processing event from Partition Id: '{partitionId}', Owner: '{guid}', EventHubPath: 'my-eventhub-preprod'
```

and

```
Error processing event from Partition Id: '{partitionId}', Owner: '{guid}', EventHubPath: 'my-eventhub-prod'
```

where the EventHub path is always the same for each result.

This is the stack trace:

```
System.AggregateException:
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError (Microsoft.Extensions.Logging, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Logging.Logger.BeginScope (Microsoft.Extensions.Logging, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Logging.LoggerExtensions.BeginFunctionScope (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\Logger\LoggerExtensions.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 70)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__15.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 85)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutorExtensions+<TryExecuteAsync>d__0.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutorExtensions.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 34)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1+<TryExecuteAsync>d__7.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 59)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.EventHubs.EventHubListener+EventProcessor+<TryExecuteWithLoggingAsync>d__13.MoveNext (Microsoft.Azure.WebJobs.EventHubs, Version=4.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.EventHubs.EventHubListener+EventProcessor+<ProcessEventsAsync>d__12.MoveNext (Microsoft.Azure.WebJobs.EventHubs, Version=4.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.EventHubs.Processor.PartitionPump+<ProcessEventsAsync>d__30.MoveNext (Microsoft.Azure.EventHubs.Processor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
Inner exception System.InvalidCastException handled at Microsoft.Extensions.Logging.Logger.ThrowLoggingError:
   at System.Collections.Generic.DictionaryExtensions.GetValueOrDefault (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Shared\DictionaryExtensions.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 13)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.StartTelemetryIfFunctionInvocation (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 475)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.BeginScope (Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.csMicrosoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 442)
   at Microsoft.Extensions.Logging.ScopeLogger.CreateScope (Microsoft.Extensions.Logging, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.Logging.Logger.BeginScope (Microsoft.Extensions.Logging, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

**Comment by brennfoster** [comment]
I currently have a function app (durable) running in production with two different Diagnostics dll versions loaded up in the w3 process with zero issues. It's using version 4.1.1 of the EventHub nuget package as well.

However, this week I've come across the same error messages that others have been posting in here. I'm using 4.2.0 of the EventHub nuget package and I don't have a duplicate Diagnostics dll loaded up in the w3 process.

In my circumstance I deployed a package to a brand new function app resource. There has been zero function execution since I initially deployed to the new resource. Nothing I try seems to fix.

**Comment by softnado** [comment]
Hitting the same issue. Any update on the reasons or way to solve it?

**Comment by brennfoster** [comment]
> Hitting the same issue. Any update on the reasons or way to solve it?

The only way I was able to solve is downgrading the Event Hub nuget package as others have suggested. Use 4.0.1.

**Comment by eaidland** [comment]
I'm not able to reproduce this locally, but when running in Azure I can see in app insights:
Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.

Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.26.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35


The function nugets:
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.25" />


I can't find the Microsoft.Azure.WebJobs.Logging.ApplicationInsights, Version=3.0.26.0 anywhere and latest nuget is 3.0.25

**Comment by svandekrol** [comment]
I found this same error, with an EventHub trigger.  Worked fine on my local machine, but did not work in Azure.  I rolled back from version 4.2.0 of Microsoft.Azure.WebJobs.Extensions.EventHubs to 4.0.1 and it seems to have fixed the issue.

**Comment by karwaisee** [comment]
@lmolkova 
I have the same error when I recently upgraded several nuget packages in the existing event hub triggered function app. Here is my problematic nugets combination:
```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
```

When I checked the w3p.exe in Kudu, found that there are 2 copies of `System.Diagnostics.DiagnosticSource.dll`, but both are same version (like 5.xx).

Good thing is I can simulate the exact same Exception in my local machine (as well as in Azure), so get to played around with different combination of nuget package versions. Following the recommended workaround. I downgraded `Microsoft.Azure.WebJobs.Extensions.EventHubs` from version 4.2.0 to 4.1.1, but it is still not working. However, after I downgraded the `Microsoft.ApplicationInsights.AspNetCore` from version 2.16.0 to 2.15.0, everything is back to normal and no more "Unable to cast" App Insights Exception. When I switch back the event hubs extension version to 4.2.0, everything are still working fine.

So this is my final nuget packages that works. Hope this helps if anyone encounter the same issue. And also, development team can look into the possible root cause.
```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
```

**Comment by shraddha1491** [comment]
Facing the same issue with event hub trigger, not able to repro locally.
System.Diagnostics.DiagnosticSource is loaded just once.

![image](https://user-images.githubusercontent.com/46517087/116950311-74f10d00-ac39-11eb-8da5-1c20d2a3e29e.png)

 <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

**Comment by brennfoster** [comment]
Is this ever going to get fixed? I would like to start using the new features that come in 4.2.0.

![image](https://user-images.githubusercontent.com/419283/120836385-c0415880-c522-11eb-8bc5-cd2da3b1dc35.png)

**Comment by johnkostyrka** [comment]
Check you are using .Net Core 3.1 LTS, nothing older

**Comment by brennfoster** [comment]
Function Runtime ~3 uses LTS (.NET Core 3.1). It's not something I need to configure.

**Comment by josh-endries** [comment]
Almost 1.5 years now with no response?

**Comment by karwaisee** [comment]
@brennfoster , have you tried downgrading the App Insights package? For my project, the buggy package is actually from App Insights, working well with EventHubs v4.2.0

This is my working nuget combination:
```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
```

**Comment by brennfoster** [comment]
I don't need to write any custom telemetry so I don't use the app insights package. The built in logger forwards to app insights when you have the instrumentation key set in app settings.

**Comment by michaeldaw** [comment]
Downgrading to 4.0.1 worked for me as well. Had to clean the solution and re-deploy to azure.

A fix would be much appreciated.

**Comment by sukhdeepsingh1** [comment]
It has been more than 1.5 years, but this issue is still there (with v4.2.0) and v5 packages have other major issues related to dependency tree loading. Will it be there even with the .Net 6 function app? if yes, then we should look for some other platform rather than function app.

**Comment by chdalski** [comment]
For us the the following configuration for functions runtime version 3 fixed it:

Function App Configuration (in portal see settings -> configuration -> application settings)
NAME: `EVENT_LISTENER`
VALUE: `Endpoint=sb://<event-hub-namespace-name>.servicebus.windows.net/;SharedAccessKeyName=event_listener;SharedAccessKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=;EntityPath=<event-hub-name>`
* Note: EntityPath at the end (value):


Function App `host.json`:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  },
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 256,
        "prefetchCount": 512
      }
    }
  }
}
```
* Note *extensionBundle* version configuration
* Note eventHub extension configuration


Function `function.json`
```
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessage",
      "direction": "in",
      "eventHubName": "<event-hub-name>",
      "connection": "EVENT_LISTENER",
      "cardinality": "one",
      "consumerGroup": "$Default"
    },
  ],
  "scriptFile": "../dist/<function-name>/index.js"
}
```
* Note "eventHubName" needs to match the EntityPath value in your app configuration value
* Note connection is the name of your app configuration name

Another hint:
If you want to configure your `function.json` -> `eventHubName` via an app configuration you need to add the name enclosed in % -> i. e. %MY_APP_CONFIGURATION_NAME%

Good luck :-)

**Comment by alrod** [comment]
fix is planed in webjobs SDK for V3 function runtime:
https://github.com/Azure/azure-webjobs-sdk/issues/2828

Known workarounds:
Using EventHub extension EventHub extension <= 4.0.1 or >= 5.0.0
Using V4 function runtime,

**Comment by ganeshkadam9503** [comment]
> Getting this periodically from the EventHubListener. Any help is appreciated.
> 
> Time 4:56:17 PM Exception type System.AggregateException Exception message Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'. LogLevel Error Category Host.Triggers.EventHub HostInstanceId 41890ee6-adff-43c7-aec1-25745d35eb7d System.AggregateException: An error occurred while writing to logger(s). (Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'. at System.Collections.Generic.DictionaryExtensions.GetValueOrDefault[T](IDictionary`2 dictionary, String key) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Shared\DictionaryExtensions.cs:line 13 at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.StartTelemetryIfFunctionInvocation(IDictionary`2 stateValues) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 468 at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.BeginScope[TState](TState state) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 435 at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state) --- End of inner exception stack trace --- at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state) at Microsoft.Extensions.Logging.LoggerExtensions.BeginFunctionScope(ILogger logger, IFunctionInstance functionInstance, Guid hostInstanceId) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\Logger\LoggerExtensions.cs:line 64 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 110 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87 at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56 at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.EventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 messages) at Microsoft.Azure.EventHubs.Processor.PartitionPump.ProcessEventsAsync(IEnumerable`1 events) ---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Diagnostics.Activity]' to type 'System.Collections.Generic.IEnumerable`1[System.Diagnostics.Activity]'. at System.Collections.Generic.DictionaryExtensions.GetValueOrDefault[T](IDictionary`2 dictionary, String key) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Shared\DictionaryExtensions.cs:line 13 at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.StartTelemetryIfFunctionInvocation(IDictionary`2 stateValues) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 468 at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.BeginScope[TState](TState state) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 435 at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)<---

**Comment by ganeshkadam9503** [comment]
We are also facing the same issue.

we are using the event hub and app insight dll in the code for the sending the data to the event hub.

At the receiver side, we have the azure function which triggered by the event hub msg with app insight.

Normally we have the System.Diagnostics.DiagnosticSource dll version is (4.5.0) which is the dependent of the event hub dll.

but we need to add System.Diagnostics.DiagnosticSource dll version 5.0.0 .

added screenshot of the dll version
![Uploading image.png…]()

adding the DiagnosticSource dll version 5.0.0 at sender side and receiver side issue get resolved for us and working fine
